### ISSUE TITLE
Rons Track Pack Stuff not in correct Directories (I think)

### ISSUE THREAD

**Issue by Tornadokid21** [dvdvideo1234/TrackAssemblyTool#26]
So, Rons 2ft and G-scale pack are not in Track Assembly. I think the creator of TA forgot to fix Rons Packs. Please fix this when you have time.

Sincerily,
TornadoKid21 (aka. FyreLite07)

**Comment by dvdvideo1234** [comment]
Hello,

### Affected functionality
[![](https://img.youtube.com/vi/i9quRkL85r4/0.jpg)](http://www.youtube.com/watch?v=i9quRkL85r4 "")

### Description of the problem
Yes, thank you for that. I am the creator of TA and I am already aware of that ;) . [I had to fix the database export folder name as it has to be addressed to work properly][ref-commit]. In [prior versions][ref-prior] the export settings and source file for creating DSV insertion scripts were located in `.../data/autorun` which were mounted at the game start and merged with Garry's mod internal file system. This is not correct, because the `.../data/autorn` was not a dedicated TA folder ( had to be `.../data/trackassebly/...` ) and it was messing with some export functionality of the tool, so I created a new dedicated folder for settings, which I named [`set`][ref-set] so TA can access it. I had to [move the DSV file list][ref-dsv] in [that][ref-set] folder.

### Problem resolution
To fix the external databases for [`Ron's Gscale`][ref-rongs] and [`Ron's 2ft`][ref-ron3ft] ( Or all the others regarding ) the easiest way is to just delete the [`.../data/trackassembly`][ref-tadata] folder and start the game again. That way you will make TA to recreate all the folders with the new arrangement for you. You can also adjust all the files/folders yourself. It is possible but it is quite hard as it needs a lot of debugging. Just let TA configuration recreate itself as it will be triggered on autorun anyway.

### Author notes and warnings
**Note: Backup you personal [`DSV`][ref-dsv] [databases][ref-datadsv] if any, so you can add [`them`][ref-datadsv] back after you make the transition!**
**Note: When you open the video you can see `TA/data/autosave/z_autorun_[trackassembly].txt` and this is incorrect!**

Good luck!

[ref-dsv]: https://github.com/dvdvideo1234/TrackAssemblyTool/blob/master/data/trackassembly/set/trackasmlib_dsv.txt
[ref-set]: https://github.com/dvdvideo1234/TrackAssemblyTool/tree/master/data/trackassembly/set
[ref-commit]: https://github.com/dvdvideo1234/TrackAssemblyTool/commit/29b0bff59cea1a4322a4d34e97dde9b7fb8c87fc
[ref-prior]: https://github.com/dvdvideo1234/TrackAssemblyTool/tree/7a78a7dfc0dc1f6067433af1bf93609c5fb650b7
[ref-rongs]: https://steamcommunity.com/sharedfiles/filedetails/?id=865735701
[ref-ron3ft]: https://steamcommunity.com/sharedfiles/filedetails/?id=634000136
[ref-tadata]: https://github.com/dvdvideo1234/TrackAssemblyTool/tree/master/data/trackassembly
[ref-datadsv]: https://github.com/dvdvideo1234/TrackAssemblyTool/tree/master/data/trackassembly/dsv

**Comment by Gleb90809** [comment]
Hello! I really like your map gm_tramtown, it’s very atmospheric and well-designed.
However, I’m experiencing problems with missing textures (pink and black checkerboards in many areas).

I have all the following Source games installed and mounted in Garry’s Mod:

Half-Life 2

Half-Life 2: Episode One

Half-Life 2: Episode Two

Half-Life 1

Counter-Strike: Source

Team Fortress 2

Left 4 Dead 2

All of them are working and mounted correctly in GMod.

Could it be that some custom textures or models were not included with the map?
If there’s a fix pack or updated version, I’d really appreciate a link.

Thanks again for the awesome work!

**Comment by dvdvideo1234** [comment]
@Gleb90809 

It seems you are confusing me with someone else.[ I did not make this map](https://steamcommunity.com/sharedfiles/filedetails/?id=3430433527) ;)

You probably did not pay attention and forgot to subscribe to [the required items](https://steamcommunity.com/workshop/filedetails/?id=634000136) given [by the author](https://steamcommunity.com/profiles/76561198166140758).
